// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufnpnprsaiqdgerdosdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbnBucHJzYWlxZGdlcmRvc2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzAxODcsImV4cCI6MjA1OTU0NjE4N30.WEJ6f-sEp9QOYj9zBg5yA01Zrqp-5PkLro5ZTWFn79c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);